const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {VM,Fault}=require('../web/runtime.js');require('../web/compiled.js');
const project=global.EMM_PROJECT;
let checks=0;
function test(name,fn){fn();checks++;console.log('PASS',name);}
function vmFor(name,seed=1337){const vm=new VM(project.modules,{limit:500000});vm.root.get('$26')(BigInt(seed));vm.load(project.modules['games/'+name+'.emm']);return vm;}
test('all seven lessons execute with exact expected output',()=>{for(const l of project.lessons){let output=[];new VM({}, {output:s=>output.push(s)}).load(l.ir);assert.equal(output.join('\n'),l.expected);}});
test('compiled game sources match their source hashes',()=>{const crypto=require('node:crypto');for(const [name,hash]of Object.entries(project.hashes)){let source=fs.readFileSync(path.join(__dirname,'..',name),'utf8');assert.equal(crypto.createHash('sha256').update(source).digest('hex'),hash);assert.equal(project.sources[name].emm,source);}});
test('2048 merges once per turn, scores, restores with undo, and does not spawn on no-op',()=>{let vm=vmFor('merge'),e=vm.scope;e.set('score',0n);assert.deepEqual(vm.call('merge',[2n,2n,2n,2n]),[4n,4n,0n,0n]);assert.equal(e.get('score'),8n);e.set('board',[2n,2n,...Array(14).fill(0n)]);e.set('score',0n);assert.equal(vm.call('move','left'),true);assert.equal(e.get('board')[0],4n);assert.equal(e.get('score'),4n);assert.equal(e.get('moves'),1n);vm.call('undo');assert.deepEqual(e.get('board'),[2n,2n,...Array(14).fill(0n)]);assert.equal(e.get('score'),0n);assert.equal(e.get('moves'),0n);e.set('board',[2n,4n,8n,16n,...Array(12).fill(0n)]);assert.equal(vm.call('move','left'),false);assert.deepEqual(e.get('board'),[2n,4n,8n,16n,...Array(12).fill(0n)]);});
test('2048 detects exhausted boards and victory',()=>{let vm=vmFor('merge'),e=vm.scope;e.set('board',[2n,4n,2n,4n,4n,2n,4n,2n,2n,4n,2n,4n,4n,2n,4n,2n]);assert.equal(vm.call('available'),false);vm.call('merge',[1024n,1024n,0n,0n]);assert.equal(e.get('won'),true);});
test('dungeon generator preserves a reachable exit across 100 seeds',()=>{for(let seed=0;seed<100;seed++){let vm=vmFor('dungeon',seed),tiles=vm.scope.get('tiles');let todo=[12],seen=new Set(todo);while(todo.length){let i=todo.shift();for(let j of [i-1,i+1,i-11,i+11])if(j>=0&&j<121&&tiles[j]!==1n&&!seen.has(j)){seen.add(j);todo.push(j);}}assert(seen.has(108));const enemies=vm.scope.get('enemies');assert.equal(new Set(enemies.map(m=>m.x+','+m.y)).size,enemies.length);assert(enemies.every(m=>tiles[Number(m.y*11n+m.x)]!==1n));}});
test('dungeon combat, leveling, potions, stairs, loss, and final victory are EMM outcomes',()=>{
  let vm=vmFor('dungeon'),e=vm.scope,h=e.get('hero');e.set('enemies',[]);e.get('tiles')[13]=0n;e.set('enemies',[{x:2n,y:1n,hp:1n,attack:1n,boss:false}]);vm.call('act','right');assert.equal(e.get('kills'),1n);assert.equal(h.xp,1n);assert.equal(h.x,1n);vm.call('gain');vm.call('gain');assert.equal(h.level,2n);assert.equal(h.attack,6n);
  h.hp=4n;h.potions=1n;e.set('enemies',[]);vm.call('act','potion');assert.equal(h.hp,18n);assert.equal(h.potions,0n);assert.equal(vm.call('act','potion'),false);
  h.x=8n;h.y=9n;e.get('tiles')[108]=3n;vm.call('act','right');assert.equal(e.get('floor'),2n);assert.equal(h.x,1n);
  h.x=8n;h.y=9n;e.set('floor',5n);e.set('bossDead',true);e.set('enemies',[]);e.get('tiles')[108]=3n;vm.call('act','right');assert.equal(e.get('phase'),'won');assert.equal(vm.call('act','wait'),false);
  vm.call('start');h=e.get('hero');h.hp=1n;e.set('enemies',[{x:2n,y:1n,hp:99n,attack:10n,boss:false}]);vm.call('act','wait');assert.equal(e.get('phase'),'lost');assert.equal(h.hp,0n);
});
test('poker draw never duplicates cards, locks after reveal, and accounts for outcomes',()=>{for(let seed=0;seed<100;seed++){const vm=vmFor('poker',seed),e=vm.scope;vm.call('select',0n);vm.call('select',2n);vm.call('draw');const cards=[...e.get('player'),...e.get('dealer')].map(c=>c.rank+':'+c.suit);assert.equal(new Set(cards).size,10);assert.equal(e.get('phase'),'reveal');assert.equal(e.get('wins')+e.get('losses')+e.get('ties'),1n);vm.call('draw');assert.equal(e.get('rounds'),1n);vm.call('deal');assert.equal(e.get('phase'),'draw');assert.equal(e.get('rounds'),1n);}});
test('poker evaluator matches independent Python oracle fixtures',()=>{let vm=vmFor('poker');let fixtures=JSON.parse(fs.readFileSync(path.join(__dirname,'poker-oracle.json'),'utf8'));let poker=vm.scope.get('poker');for(let f of fixtures){vm.resetBudget();const hand=f.hand.map(([rank,suit])=>({rank:BigInt(rank),suit}));assert.deepEqual(vm.invoke(poker.evaluate,[hand]).map(Number),f.score);}assert.equal(fixtures.length,1010);});
test('faults report source locations and execution budget is enforced',()=>{let vm=vmFor('merge');assert.throws(()=>vm.call('merge',[true,true]),Fault);const loop=[{tag:'while',loc:['test.emm',1,1],value:{tag:'literal',value:true},body:[]}];assert.throws(()=>new VM({}, {limit:100}).load(loop),/budget/);});
console.log(`${checks} browser checks passed.`);
