#!/usr/bin/env python3
"""Build browser assets from real EMM sources using emmc's frontend/IR."""
import hashlib
import json
import pathlib
import sys
sys.path.insert(0,str(pathlib.Path(__file__).resolve().parents[1]))
import emmc

ROOT=pathlib.Path(__file__).resolve().parents[1]
LESSONS=[
 ('hello','01 · Say hello','...! "Hello, World!"','Printing is ...! in EMM and 😭 in its sister language. Strings stay readable in both.','Hello, World!'),
 ('variables','02 · Remember things','... name = "Lucas"\n... age = 13\n! age = age + 1\n...! name + " is " + ...?? $4(age)','... declares a variable. ! changes it. $4 converts a value to text.','Lucas is 14'),
 ('branches','03 · Make a decision','... score = 85\n?? score >= 80 { ...! "We ARE COKKING" }\n??? score >= 60 { ...! "Keep going" }\n???? { ...! "Try again" }','The first true branch runs. Comparisons produce booleans. Else-if and else complete the choice.','We ARE COKKING'),
 ('loops','04 · Repeat with a purpose','... total = 0\n..... i : ...?? $9(1, 6)\n{\n    ! total = total + i\n}\n...! total','A for-each loop walks a collection. $9(1, 6) gives 1 through 5; the end is excluded.','15'),
 ('functions','05 · Build your own tool','??... factorial(n)\n{\n    ?? n <= 1 { !... 1 }\n    !... n * ...?? factorial(n - 1)\n}\n...! ...?? factorial(6)','Functions take parameters and return values. This recursive function multiplies 6 × 5 × 4 × 3 × 2 × 1.','720'),
 ('collections','06 · Model a game world','... hero = {name: "Lucas", hp: 20}\n... inventory = ["potion", "key"]\n! hero.hp = hero.hp - 3\n...?? $7(inventory, "treasure")\n...! hero.name + ": " + ...?? $4(hero.hp) + " HP"\n...! inventory','Records hold named fields. Lists hold indexed values. Both are mutable and can represent a complete game state.','Lucas: 17 HP\n[potion, key, treasure]'),
 ('errors','07 · Recover and continue','?:\n{\n    ...! 10 / 0\n}\n?!! error\n{\n    ...! "Caught: " + error\n}\n...! "Still running."','Try/catch turns a runtime fault into an outcome you can handle. Return and break remain separate control flow.','Caught: Division by zero\nStill running.'),
]
def browser_ir(value):
 if isinstance(value,dict):
  out={k:browser_ir(v) for k,v in value.items()}
  if out.get('tag')=='literal' and type(value.get('value')) is int:
   out['integerText']=str(value['value']);out['value']=None
  if 'loc' in out: out['loc'][0]=pathlib.Path(out['loc'][0]).relative_to(ROOT).as_posix()
  return out
 if isinstance(value,(list,tuple)):return [browser_ir(x) for x in value]
 return value
def build():
 modules={};sources={};hashes={}
 for path in sorted(list((ROOT/'games').glob('*.emm'))+[ROOT/'examples/pokerlib.emm']):
  key=path.relative_to(ROOT).as_posix();source=path.read_text(encoding='utf-8')
  modules[key]=browser_ir(emmc.parse(source,path,'emm'))
  sources[key]={'emm':source,'cry':emmc.translate(source,path,'cry')}
  hashes[key]=hashlib.sha256(source.encode()).hexdigest()
 lessons=[]
 for key,title,source,description,expected in LESSONS:
  file=ROOT/'lessons'/f'{key}.emm';file.parent.mkdir(exist_ok=True)
  file.write_text(source+'\n',encoding='utf-8');cry=emmc.translate(source,file,'cry');file.with_suffix('.cry').write_text(cry,encoding='utf-8')
  lessons.append(dict(id=key,title=title,description=description,expected=expected,emm=source,cry=cry,ir=browser_ir(emmc.parse(source,file,'emm'))))
 payload={'modules':modules,'sources':sources,'hashes':hashes,'lessons':lessons}
 (ROOT/'web/compiled.js').write_text('// Generated by scripts/build_web.py. Do not edit game logic here.\nglobalThis.EMM_PROJECT = '+json.dumps(payload,ensure_ascii=False,separators=(',',':'))+';\n',encoding='utf-8')
 print(f'Built {len(modules)} EMM modules and {len(lessons)} runnable lessons.')
if __name__=='__main__':build()
